/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.reply.kotlin-library-conventions")
}

dependencies {
    api(project(":lib"))
}
