/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.reply.kotlin-application-reactive-conventions")
    kotlin("plugin.spring") version "1.8.22"
}

dependencies {
    api(project(":lib"))
    implementation("org.springframework.cloud:spring-cloud-starter-gateway")
    implementation("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-authorization-server")
}

application {
    // Define the main class for the application.
    mainClass.set("com.reply.gateway.AppKt")
}
