package com.reply.authorizationserver

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity


@SpringBootApplication
@EnableWebSecurity
class AuthorizationServerApplication