server:
  port: 8080
eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: "http://localhost:8081/eureka"
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
spring:
  application:
    name: "gateway"
  main:
    web-application-type: reactive
management:
  tracing:
    sampling:
      probability: 1.0